In [1]:
Encoding = "All, ok"
print(Encoding)


All, ok


In [8]:
# Let me import the Pandas 

In [25]:
import pandas as pd

# Data

- This below is my data

In [26]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [27]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

# scikit-learn

- Let me install it and keep inside the - Requirement.txt section

In [13]:
pip install scikit-learn


   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 229.9 kB/s eta 0:00:47
   - -------------------------------------- 0.5/11.1 MB 229.9 kB/s eta 0:00:47
   - -------------------------------------- 0.5/11.1 MB 229.9 kB/s eta 0:00:47
   - -------------------------------------- 0.5/11.1 MB 229.9 kB/s eta 0:00:47
   - -------------------------------------- 0.5/11.1 MB 229.9 kB/s eta 0:00:47
   -- ------------------------------------- 

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

# [ "CountVectorizer" ] - 
# creat a object vector for "CountVectorizer"
- Now here I am going to creat a object vector for this - [ "CountVectorizer" ]
- If we want to know more in detail we can chech this official Document - 
- URL - [https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html ]

- Convert a collection of text documents to a matrix of token counts. ( Token Counts means its talking about the - BOW - ( Bag-OF-Words )

- Lets say, Below is my data 

In [29]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [30]:
BOW = CountVectorizer()

- SO, Inside the "Data" which cloumn, I need to pass through this particular Class.

- We need to pass this "Text" Column

- So, here I can take the "Text" column and I can pass this to the - ["CountVectorizer"]

In [31]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

- So, here above is my data and simple I will take the "Object" of it - "BOW"

- SO, Here is mY "BOW". I will call the "Fit_Transform". Then I will pass the "Data" & "Text"

- I will keep this inside the variable name as a  - ("Document_matrix")

- As outcome, we can see detail of it, it showing me that - [ dtype - 'int64' | shape of the metrix (4, 5) ]

In [32]:
document_matrix = BOW.fit_transform(data["text"])

In [33]:
document_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

# Vocabulary

- Now I can check with the Volcabulary also, So i will just pick "BOW" and check the parameter just press dot (.) alot of options getting to pick
- or we can say alots of parameter to select. I will pick parameter called - ('Volabulary')

- As a outcome, we can see I am getting my "Vocabulary"

- We can in the outcome 0:1:3 nothing it just a "Index". the outcome, we can match with the Theory we have learn during our Theory claas.

In [34]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

# Find Vector 

- we have learn during out Theory class how to find vector? This is the practical Representation of it.
- So, This is my variable - ( document_matrix ) & I will write Zero top on it.
- On zero [0] top of it, I will call or write "2Array".
- As a outcome we can see we are getting our 1st "Vector". Vector of my 1st Sentence.

# People: 3 | Watch: 4| Circket:1 | Give:2 | Comment: 0

In [35]:
document_matrix[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 5)>

In [36]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]])

# Total 4 vectors.

- Similar way if want to find our other. Total 4 vectors. This way we can find it.

- 1st "Vector".  [0] Vector of my 1st Sentence.
- 2nd "Vector". [1] Vector
- 3rd "Vector". [2] Vector
- 4th "Vector". [3] Vector

# "Alphabetical Sequenc" 

- The outcome, we can see that, they are arranging it into the - "Alphabetical Sequenc" 

- We did same in Theroy, so this is how we can find out the BOW - ["Bag-OF-Words"]

In [37]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

In [38]:
document_matrix[2].toarray()

array([[1, 0, 1, 1, 0]])

In [39]:
document_matrix[3].toarray()

array([[1, 1, 1, 0, 0]])

# Note : Home work : 
# (A) OHE - ("One-Hot Encoding") Method.

- Implement OHE - ("One-Hot Encoding (OHE)") for the below data using ANY library(for example numpy, pandas, tf, pytorch etc...)

# [D] - N- GRAMS Method. - Bigrams (N-grams with n=2)

- Lest dicussed about - N-Grams in Practically

- So, Below is my "CountVectorizer" 
- To ininlized the - "CountVectorizer". I am writing "BiGram".
- "BiGram" It means 2 pairs.
- If I want to create this - "BiGram". I need to pass this - "nram_range" iniside my "CountVectorizer".
- I am passing this (2,2) argument into this class "CountVectorizer"

- For 2 words - Bi-Gram
- For 3 words - Tri-Gram
- For 4 words - Quadri-Gram
- For 5 words - Penta-Gram

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
bigram=CountVectorizer(ngram_range=(2,2))

In [42]:
trigram=CountVectorizer(ngram_range=(3,3))

# "Bi-Gram" 
- Lets say I want to create - "Bi-Gram" from this partuclar data.
- Simple, I have to fit my data. Let me pass my data - ["Text"]
- After passing my data, I am getting my "Bi-Gram" - 

- As a outcome, we can see we have got the - "Bi-Gram" Vocab 

In [43]:
bigramvocab=bigram.fit_transform(data["text"])

In [44]:
bigramvocab

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 6)>

# This below is my "Data"

- 0   people watch cricket
- 1   cricket watch cricket
- 2   people give comment
- 3   cricket give comment

In [45]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

# Vocabulary "Bi-Gram"

- Let me check out the Vocabulary of this "Bi-Gram"
- what I am getting over here, If pick the Vocabulary of this "Bi-Gram"
- As a outcome, we can see that, it picked the 6 words

In [46]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

# uniq vocab from the above data 
- [('cricket give'),('cricket watch'),('give comment'),('people give'),('people watch'),('watch cricket')]
- {'people watch': 4, 'watch cricket': 5, 'cricket watch': 1, 'people give': 3, 'give comment': 2, 'cricket give': 0}

- people watch cricket cricket watch cricket people give comment cricket give comment

- Capture the information in sequence(count vectorizer). It will not going to jump the word inbetween

- custom logic: We can create pair as per our wish. So, Below I am going to craete 3 word pair from my data.

# Tri-Gram Vocabulary

- I alreay have the Pair of 2. So, If we want to see the 3 pairs, Then I have use the "Tri-Gram" . 
- Then, I will get piars of 3 words as a outcome from out data.

In [47]:
trigram=CountVectorizer(ngram_range=(3,3))

In [48]:
trigramvocab=trigram.fit_transform(data["text"])

In [49]:
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

# Mix pair
 
- Here I am going to create a Mix pair. 
- I will be calling the "Fit_Transfer". The, I will be passing the "Data"
- This will be my Mix-Vocabulary.

- Here, As our Final outcome, we can see that, we are getting out Mix_ Vocabulary.

- Inside this "mix.vocabulary_". If I am writting the "ngram_range=(1,3))"
- Because of this (1,3). I am getting the data.
- 1."Single",
- 2"Pair" and
- 3."Trigram"

In [50]:
mix=CountVectorizer(ngram_range=(1,3))

In [51]:
mix_vocab=mix.fit_transform(data["text"])

# mix Vocabulary

In [52]:
mix.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

# Next Class "Agenda" will be

- 1.TF-IDF
- 2.Word2Vec
- 3.Hugging Face Senetnce Embedding

# 1.TF-IDF Method - [ Term Frequency-Inverse Document Frequency ] Method

- Below is my data. This is the same data, Which one i have used above.

In [53]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

- Above "Data" I am actually feeding to this Class - ["TfidfVectorizer"]
- This is my "TF-IDF vectorize class" , We have to import from the "Sklearn" 

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

- And Below is my "Object" of TF-IDF vector.

In [55]:
tfidf=TfidfVectorizer()

- Once I pass the the "Data" to it. As a outcome, we can see I am getting my ["Vectors"]
- This outcome is my "TF-IDF" vector of the given data.
- Below outcome is, Its a "LogBase 10".
- 
# Sparsity
-  We can notice that - inside our outcome, Zero (0), Zero(0) inbetween. Its representing to the Sparcity.

# Outcome
-  This way it given me the outcome as a vector of all my data, of all my Sentences.

1. 0     people watch cricket   - outcome we can see - [0.        , 0.49681612, 0.        , 0.61366674, 0.61366674]
2. 1    cricket watch cricket   - outcome we can see - [0.        , 0.8508161 , 0.        , 0.        , 0.52546357]

In [56]:
import numpy as np

In [57]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

# Vocabulary ( Vocab )

- If we go & check the numer of feature vecubalory(Vocab).
- This is my vocab -  ['comment' 'cricket' 'give' 'people' 'watch']

- The outcome is this is way came - ['comment' 'cricket' 'give' 'people' 'watch']. 
- But in Notebook, I made a notes the Calculation this way -['cricket''comment' 'give' 'people' 'watch']
- 

In [58]:
feature_names = tfidf.get_feature_names_out()

print("Feature Names:", feature_names)

Feature Names: ['comment' 'cricket' 'give' 'people' 'watch']


# Note :

- "TF" vector is not there, if there then we can write this way - ["tfidf.idf_"].
- But, its not there we have, only we have the "IDF" vector, we can see below

# Is ["TF_IDF"] is Embedding?
- No, its a Endcoding, why because we are just calculating the Frequency only, we are not using the "Neural Network(NN)"

# Is the ["BM_25"] is Embedding?
- No, Its again it a Extended version of "TF-IDF" itself. So, Again its a Frequency base technique.
- It's a Encoding Technique.

In [59]:

tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])

# Notebook Fomula calulation.
-  So, we did some calculation in Vocabulary (vocab). Formula Calculaion in our Notebook.
- If we solve this particular term - 1/3*log(4/3)

- From ["D1"] - 1/3*log(4/3)
- Below we can see the outcome, this is the "Value"

In [60]:
np.log(4/3)

np.float64(0.28768207245178085)

- This particulat Value, I am going to multiple by 1/3. with np.log(4/3)
- Note :
- Its already taking the ["Log10"]. So, because of that the calculation here and there.
- We as a outcome, we are geeting [0.95]. Again , see this "log(4/3)" . Might be they are taking above different value of the "Log".
- Here, we are just for experiment doing below one. To understand the logic how its working behind a calculation done.

In [61]:
(1/3)*np.log(4/3)

np.float64(0.09589402415059362)

# Note :
- So, we can see we have taken "Log10" basically in fomula.
- So, we are geeting the correct solution. We just need to put correct "Log10"

In [62]:
np.log10(4/3)*(1/3)

np.float64(0.041646245536099975)